const GAMES = [
  { name: "Thracia 776",
    slug: "th",
    freeUnits: ["Leif","Safy","Eyvel","Lara"], 
    units: [
      { name : "Finn", pickRate: 120},
      { name : "Osian", pickRate: 120},
      { name : "Halvan", pickRate: 50},
      { name : "Dagdar", pickRate: 120},
      { name : "Tanya", pickRate: 20},
      { name : "Marty", pickRate: 20},
      { name : "Ronan", pickRate: 20},
      { name : "Lifis", pickRate: 65},
      { name : "Machyua", pickRate: 35},
      { name : "Brighton", pickRate: 45},
      { name : "Fergus", pickRate: 150},
      { name : "Karin", pickRate: 70},
      { name : "Dalsin", pickRate: 25},
      { name : "Asbel", pickRate: 130},
      { name : "Nanna", pickRate: 45},
      { name : "Hicks", pickRate: 35},
      { name : "Shiva", pickRate: 35},
      { name : "Carrion", pickRate: 25},
      { name : "Selphina", pickRate: 35},
      { name : "Cain", pickRate: 20},
      { name : "Alba", pickRate: 20},
      { name : "Robert", pickRate: 20},
      { name : "Fred", pickRate: 35},
      { name : "Olwen", pickRate: 35},
      { name : "Mareeta", pickRate: 35},
      { name : "Salem", pickRate: 45},
      { name : "Perne", pickRate: 45},
      { name : "Troude", pickRate: 25},
      { name : "Tina", pickRate: 50},
      { name : "Glade", pickRate: 40},
      { name : "Deen", pickRate: 50},
      { name : "Eda", pickRate: 27},
      { name : "Homer", pickRate: 35},
      { name : "Linoan", pickRate: 35},
      { name : "Ilios", pickRate: 35},
      { name : "Sleuf", pickRate: 50},
      { name : "Misha", pickRate: 20},
      { name : "Sara", pickRate: 40},
      { name : "Shannam", pickRate: 10},
      { name : "Miranda", pickRate: 10},
      { name : "Xavier", pickRate: 10},
      { name : "Amalda", pickRate: 30},
      { name : "Conomor", pickRate: 10},
      { name : "Diarmuid", pickRate: 15},
      { name : "Saias", pickRate: 30},
      { name : "Ced", pickRate: 30},
      { name : "Galzus", pickRate: 20},
  ],
},
  {
    name: "Binding Blade",
    slug: "bi",
    freeUnits: ["Roy","Marcus","Lalum","Elffin","Fae"],
    units: [
      { name: "Melady", pickRate: 480 },
      { name: "Rutger", pickRate: 410 },
      { name: "Perceval", pickRate: 320 },
      { name: "Dieck", pickRate: 65 },
      { name: "Shanna", pickRate: 480 },
      { name: "Alen", pickRate: 470 },
      { name: "Lance", pickRate: 470 },
      { name: "Clarine", pickRate: 65 },
      { name: "Lilina", pickRate: 20 },
      { name: "Lugh", pickRate: 65 },
      { name: "Klein", pickRate: 45 },
      { name: "Zeiss", pickRate: 30 },
      { name: "Tate", pickRate: 75 },
      { name: "Sin", pickRate: 100 },
      { name: "Cecilia", pickRate: 30 },
      { name: "Igrene", pickRate: 30 },
      { name: "Saul", pickRate: 55 },
      { name: "Zelot", pickRate: 45 },
      { name: "Niime", pickRate: 35 },
      { name: "Elen", pickRate: 25 },
      { name: "Astolfo", pickRate: 25 },
      { name: "Echidna", pickRate: 25 },
      { name: "Raigh", pickRate: 20 },
      { name: "Sue", pickRate: 25 },
      { name: "Ward", pickRate: 25 },
      { name: "Lot", pickRate: 25 },
      { name: "Chad", pickRate: 25 },
      { name: "Geese", pickRate: 18 },
      { name: "Hugh", pickRate: 15 },
      { name: "Fir", pickRate: 45 },
      { name: "Juno", pickRate: 15 },
      { name: "Karel", pickRate: 5 },
      { name: "Wolt", pickRate: 20 },
      { name: "Bors", pickRate: 20 },
      { name: "Trec", pickRate: 35 },
      { name: "Noah", pickRate: 60 },
      { name: "Gonzalez", pickRate: 25 },
      { name: "Douglas", pickRate: 20 },
      { name: "Dayan", pickRate: 25 },
      { name: "Dorothy", pickRate: 15 },
      { name: "Ogier", pickRate: 20 },
      { name: "Sophia", pickRate: 10 },
      { name: "Garret", pickRate: 20 },
      { name: "Yoder", pickRate: 15 },
      { name: "Bartre", pickRate: 25 },
      { name: "Barthe", pickRate: 15 },
      { name: "Gwendolyn", pickRate: 5 },
      { name: "Cath", pickRate: 15 },
    ],
  },
  {
    name: "Blazing Blade",
    slug: "bl",
    freeUnits: ["Eliwood", "Hector", "Lyn","Ninian","Nils","Merlinus","Athos"],
    units: [
      { name: "Florina", pickRate: 80 },
      { name: "Sain", pickRate: 75 },
      { name: "Pent", pickRate: 75 },
      { name: "Marcus", pickRate: 70 },
      { name: "Raven", pickRate: 70 },
      { name: "Kent", pickRate: 65 },
      { name: "Priscilla", pickRate: 65 },
      { name: "Heath", pickRate: 65 },
      { name: "Oswin", pickRate: 60 },
      { name: "Erk", pickRate: 55 },
      { name: "Canas", pickRate: 55 },
      { name: "Fiora", pickRate: 55 },
      { name: "Lowen", pickRate: 50 },
      { name: "Farina", pickRate: 50 },
      { name: "Lucius", pickRate: 45 },
      { name: "Harken", pickRate: 45 },
      { name: "Serra", pickRate: 40 },
      { name: "Rath", pickRate: 40 },
      { name: "Hawkeye", pickRate: 40 },
      { name: "Louise", pickRate: 40 },
      { name: "Jaffar", pickRate: 40 },
      { name: "Rebecca", pickRate: 35 },
      { name: "Matthew", pickRate: 35 },
      { name: "Guy", pickRate: 35 },
      { name: "Dart", pickRate: 35 },
      { name: "Nino", pickRate: 35 },
      { name: "Isadora", pickRate: 35 },
      { name: "Wil", pickRate: 30 },
      { name: "Dorcas", pickRate: 30 },
      { name: "Legault", pickRate: 30 },
      { name: "Geitz", pickRate: 30 },
      { name: "Karel", pickRate: 25 },
      { name: "Vaida", pickRate: 25 },
      { name: "Wallace", pickRate: 20 },
      { name: "Bartre", pickRate: 20 },
      { name: "Karla", pickRate: 15 },
      { name: "Renault", pickRate: 15 },
    ],
  },
    {
    name: "Sacred Stones",
    slug: "ss",
    freeUnits: ["Eirika", "Ephraim","Tethys"],
    notes: "ban seth lol",
    units: [
      { name: "Seth", pickRate: 400 },
      { name: "Vanessa", pickRate: 250 },
      { name: "Franz", pickRate: 200 },
      { name: "Cormag", pickRate: 80 },
      { name: "Tana", pickRate: 30 },
      { name: "Gerik", pickRate: 60 },
      { name: "Duessel", pickRate: 150 },
      { name: "Saleh", pickRate: 100 },
      { name: "Lute", pickRate: 85 },
      { name: "Artur", pickRate: 100 },
      { name: "Joshua", pickRate: 40 },
      { name: "Myrrh", pickRate: 50 },
      { name: "Kyle", pickRate: 50 },
      { name: "Ross", pickRate: 45 },
      { name: "Forde", pickRate: 45 },
      { name: "Innes", pickRate: 45 },
      { name: "Moulder", pickRate: 50 },
      { name: "Gilliam", pickRate: 65 },
      { name: "Syrene", pickRate: 20 },
      { name: "Garcia", pickRate: 40 },
      { name: "Natasha", pickRate: 25 },
      { name: "Colm", pickRate: 35 },
      { name: "Dozla", pickRate: 45 },
      { name: "L'Arachel", pickRate: 20 },
      { name: "Neimi", pickRate: 20 },
      { name: "Amelia", pickRate: 20 },
      { name: "Knoll", pickRate: 15 },
      { name: "Ewan", pickRate: 15 },
      { name: "Marisa", pickRate: 25 },
      { name: "Rennac", pickRate: 20 },
    ],
  },
  { name: "Path of Radiance", slug: "po", 
    freeUnits: ["Ike","Reyson","Sothe","Tibarn","Naesala","Giffca"], 
    units: [
      { name: "Titania", pickRate: 200 },     
      { name: "Oscar", pickRate: 350 },      
      { name: "Boyd", pickRate: 150 },      
      { name: "Rhys", pickRate: 75 },      
      { name: "Shinon", pickRate: 20 },      
      { name: "Gatrie", pickRate: 45 },     
      { name: "Soren", pickRate: 180 },      
      { name: "Mia", pickRate: 50 },      
      { name: "Kieran", pickRate: 200 },      
      { name: "Ilyana", pickRate: 25 },      
      { name: "Mist", pickRate: 35 },  
      { name: "Rolf", pickRate: 10 },     
      { name: "Marcia", pickRate: 600 },      
      { name: "Lethe", pickRate: 50 },      
      { name: "Mordecai", pickRate: 45 },      
      { name: "Volke", pickRate: 80 },  
      { name: "Jill", pickRate: 500 },     
      { name: "Astrid", pickRate: 150 },      
      { name: "Makalov", pickRate: 50 },      
      { name: "Tormod", pickRate: 35 },      
      { name: "Muarim", pickRate: 50 },  
      { name: "Stefan", pickRate: 20 },     
      { name: "Devdan", pickRate: 30 },      
      { name: "Tanith", pickRate: 400 },      
      { name: "Janaff", pickRate: 20 },      
      { name: "Ulki", pickRate: 20 },  
      { name: "Calill", pickRate: 65 },     
      { name: "Tauroneo", pickRate: 30 },      
      { name: "Haar", pickRate: 65 },      
      { name: "Ranulf", pickRate: 35 },      
      { name: "Bastian", pickRate: 20 },
      { name: "Lucia", pickRate: 15 },     
      { name: "Geoffery", pickRate: 55 },      
      { name: "Largo", pickRate: 35 },      
      { name: "Elincia", pickRate: 35 },      
      { name: "Nasir", pickRate: 10 },  
      { name: "Ena", pickRate: 10 },    
    ], },
  { name: "Radiant Dawn", slug: "rd", freeUnits: [], units: [] },
  { name: "Shadow Dragon", slug: "sd", 
    freeUnits: ["Marth","Jagen","Tiki","Nagi","Gotoh","Xane"], 
    units: [
      { name: "Abel", pickRate: 390 },      
      { name: "Cain", pickRate: 390 },      
      { name: "Gordin", pickRate: 0 },  
      { name: "Draug", pickRate: 0 },     
      { name: "Caeda", pickRate: 800 },      
      { name: "Wrys", pickRate: 500 },      
      { name: "Ogma", pickRate: 230 },      
      { name: "Barst", pickRate: 230 },  
      { name: "Bord", pickRate: 80 },     
      { name: "Cord", pickRate: 80 },      
      { name: "Castor", pickRate: 40 },      
      { name: "Darros", pickRate: 15 },      
      { name: "Julian", pickRate: 80 },  
      { name: "Lena", pickRate: 800 },     
      { name: "Navarre", pickRate: 25 },      
      { name: "Merric", pickRate: 50 },      
      { name: "Matthis", pickRate: 10 },      
      { name: "Hardin", pickRate: 200 },  
      { name: "Wolf", pickRate: 450 },     
      { name: "Sedgar", pickRate: 470 },      
      { name: "Roshea", pickRate: 50 },      
      { name: "Vyland", pickRate: 20 },      
      { name: "Wendell", pickRate: 650 },  
      { name: "Rickard", pickRate: 70 },     
      { name: "Athena", pickRate: 50 },      
      { name: "Bantu", pickRate: 15 },      
      { name: "Caesar", pickRate: 25 },      
      { name: "Radd", pickRate: 25 },  
      { name: "Roger", pickRate: 10 },     
      { name: "Jeorge", pickRate: 60 },      
      { name: "Maria", pickRate: 90 },      
      { name: "Minerva", pickRate: 180 },      
      { name: "Linde", pickRate: 45 },
      { name: "Jake", pickRate: 50 },     
      { name: "Midia", pickRate: 60 },      
      { name: "Dolph", pickRate: 10 },      
      { name: "Macellan", pickRate: 10 },      
      { name: "Tomas", pickRate: 10 },  
      { name: "Boah", pickRate: 390 },     
      { name: "Horace", pickRate: 20 },      
      { name: "Beck", pickRate: 45 },      
      { name: "Astram", pickRate: 45 },      
      { name: "Palla", pickRate: 70 },  
      { name: "Catria", pickRate: 70 },     
      { name: "Arran", pickRate: 25 },      
      { name: "Samson", pickRate: 25 },      
      { name: "Etzel", pickRate: 65 },  
      { name: "Est", pickRate: 10 },     
      { name: "Lorenz", pickRate: 25 },      
      { name: "Ymir", pickRate: 25 },      
      { name: "Elice", pickRate: 180 },              
    ], },
  { name: "New Mystery", slug: "nm", 
    freeUnits: ["Kris","Marth","Arran","Phina","Lena","Nyna","Maria","Elice"], 
    units: [
      { name: "Luke", pickRate: 0 },     
      { name: "Roderick", pickRate: 0 },      
      { name: "Cecil", pickRate: 0 },      
      { name: "Gordin", pickRate: 0 },      
      { name: "Ryan", pickRate: 0 },  
      { name: "Draug", pickRate: 0 },     
      { name: "Marisha", pickRate: 0 },      
      { name: "Catria", pickRate: 0 },      
      { name: "Warren", pickRate: 0 },      
      { name: "Cord", pickRate: 0 },  
      { name: "Linde", pickRate: 0 },     
      { name: "Palla", pickRate: 0 },      
      { name: "Bord", pickRate: 0 },      
      { name: "Julian", pickRate: 0 },      
      { name: "Matthis", pickRate: 0 },  
      { name: "Wrys", pickRate: 0 },     
      { name: "Ogma", pickRate: 0 },      
      { name: "Yuliya", pickRate: 0 },      
      { name: "Jubelo", pickRate: 0 },      
      { name: "Sirius", pickRate: 0 },  
      { name: "Castor", pickRate: 0 },     
      { name: "Caeda", pickRate: 0 },      
      { name: "Barst", pickRate: 0 },      
      { name: "Rickard", pickRate: 0 },      
      { name: "Frey", pickRate: 0 },  
      { name: "Norne", pickRate: 0 },     
      { name: "Samuel", pickRate: 0 },      
      { name: "Wendell", pickRate: 0 },      
      { name: "Caesar", pickRate: 0 },      
      { name: "Radd", pickRate: 0 },  
      { name: "Navarre", pickRate: 0 },     
      { name: "Cain", pickRate: 0 },      
      { name: "Bantu", pickRate: 0 },           
      { name: "Roger", pickRate: 0 },   
      { name: "Jeorge", pickRate: 0 },      
      { name: "Minerva", pickRate: 0 },  
      { name: "Etzel", pickRate: 0 },     
      { name: "Merric", pickRate: 0 },      
      { name: "Arlen", pickRate: 0 },      
      { name: "Dice", pickRate: 0 },      
      { name: "Malice", pickRate: 0 },  
      { name: "Horace", pickRate: 0 },     
      { name: "Jake", pickRate: 0 },      
      { name: "Darros", pickRate: 0 },      
      { name: "Roberto", pickRate: 0 },      
      { name: "Belf", pickRate: 0 },  
      { name: "Reiden", pickRate: 0 },     
      { name: "Beck", pickRate: 0 },
      { name: "Athena", pickRate: 0 },           
      { name: "Xane", pickRate: 0 },      
      { name: "Tiki", pickRate: 0 },      
      { name: "Est", pickRate: 0 },  
      { name: "Dolph", pickRate: 0 },  
      { name: "Macellan", pickRate: 0 },  
      { name: "Astram", pickRate: 0 },  
      { name: "Katarina", pickRate: 0 },  
      { name: "Tomas", pickRate: 0 },  
      { name: "Sheena", pickRate: 0 },  
      { name: "Samson", pickRate: 0 },  
      { name: "Frost", pickRate: 0 },  
      { name: "Roshea", pickRate: 0 },  
      { name: "Vyland", pickRate: 0 },  
      { name: "Sedgar", pickRate: 0 },  
      { name: "Wolf", pickRate: 0 },  
      { name: "Midia", pickRate: 0 },  
      { name: "Ymir", pickRate: 0 },  
      { name: "Michalis", pickRate: 0 },  
      { name: "Nagi", pickRate: 0 },  
 

    ], },
  { name: "Awakening", slug: "aw",
    notes: "",
    freeUnits: ["Robin","Chrom","Lucina","Olivia"],
    units: [
      { name: "Lissa", pickRate: 90 },  
      { name: "Frederick", pickRate: 200 },  
      { name: "Sully", pickRate: 50 },  
      { name: "Virion", pickRate: 25 },  
      { name: "Stahl", pickRate: 70 },  
      { name: "Vaike", pickRate: 40 },  
      { name: "Miriel", pickRate: 50 },  
      { name: "Sumia", pickRate: 90 },  
      { name: "Kellam", pickRate: 30 },  
      { name: "Lon'qu", pickRate: 45 },  
      { name: "Ricken", pickRate: 40 },  
      { name: "Maribelle", pickRate: 50 },  
      { name: "Panne", pickRate: 75 },  
      { name: "Gaius", pickRate: 30 },  
      { name: "Cordelia", pickRate: 90 },  
      { name: "Gregor", pickRate: 75 },  
      { name: "Nowi", pickRate: 50 },  
      { name: "Libra", pickRate: 115 },  
      { name: "Tharja", pickRate: 40 },  
      { name: "Cherche", pickRate: 20 },  
      { name: "Say'ri", pickRate: 10 },  
      { name: "Basilio", pickRate: 20 },  
      { name: "Flavia", pickRate: 25 },  
      { name: "Donnel", pickRate: 20 },  
      { name: "Anna", pickRate: 100 },  
    ], 
  },
  {
    name: "Fates Birthright",
    slug: "br",
    notes: "",
    freeUnits: ["Corrin", "Azura"],
    units: [
      { name: "Ryoma", pickRate: 300 },
      { name: "Takumi", pickRate: 100 },
      { name: "Hinoka", pickRate: 70 },
      { name: "Kaze", pickRate: 150 },
      { name: "Kagero", pickRate: 150 },
      { name: "Saizo", pickRate: 150 },
      { name: "Scarlet", pickRate: 100 },
      { name: "Silas", pickRate: 90 },
      { name: "Reina", pickRate: 155 },
      { name: "Sakura", pickRate: 75 },
      { name: "Oboro", pickRate: 75 },
      { name: "Felicia", pickRate: 80 },
      { name: "Jakob", pickRate: 80 },
      { name: "Subaki", pickRate: 40 },
      { name: "Kaden", pickRate: 25 },
      { name: "Hinata", pickRate: 25 },
      { name: "Hana", pickRate: 25 },
      { name: "Orochi", pickRate: 25 },
      { name: "Setsuna", pickRate: 25 },
      { name: "Rinkah", pickRate: 95 },
      { name: "Azama", pickRate: 55 },
      { name: "Hayato", pickRate: 90 },
      { name: "Shura", pickRate: 70 },
      { name: "Mozu", pickRate: 45 },
      { name: "Izana", pickRate: 5 },
      { name: "Yukimura", pickRate: 5 },
    ],
  },
  {
    name: "Fates Conquest",
    slug: "co",
    notes: "",
    freeUnits: ["Corrin", "Azura"],
    units: [
      { name: "Xander", pickRate: 350 },
      { name: "Camilla", pickRate: 500 },
      { name: "Leo", pickRate: 175 },
      { name: "Elise", pickRate: 100 },
      { name: "Kaze", pickRate: 60 },
      { name: "Niles", pickRate: 175 },
      { name: "Effie", pickRate: 40 },
      { name: "Silas", pickRate: 60 },
      { name: "Felicia", pickRate: 60 },
      { name: "Jakob", pickRate: 60 },
      { name: "Selena", pickRate: 50 },
      { name: "Beruka", pickRate: 45 },
      { name: "Keaton", pickRate: 45 },
      { name: "Arthur", pickRate: 40 },
      { name: "Laslow", pickRate: 50 },
      { name: "Peri", pickRate: 35 },
      { name: "Odin", pickRate: 55 },
      { name: "Charlotte", pickRate: 40 },
      { name: "Nyx", pickRate: 25 },
      { name: "Benny", pickRate: 30 },
      { name: "Flora", pickRate: 10 },
      { name: "Shura", pickRate: 20 },
      { name: "Mozu", pickRate: 40 },
      { name: "Izana", pickRate: 5 },
      { name: "Gunter", pickRate: 25 },
    ],
  },
  {
    name: "Fates Revelation",
    slug: "re",
    notes: "",
    freeUnits: ["Corrin", "Azura", "Scarlet"],
    units: [
      { name: "Ryoma", pickRate: 95 },
      { name: "Xander", pickRate: 90 },
      { name: "Camilla", pickRate: 85 },
      { name: "Takumi", pickRate: 80 },
      { name: "Leo", pickRate: 75 },
      { name: "Hinoka", pickRate: 70 },
      { name: "Kaze", pickRate: 65 },
      { name: "Kagero", pickRate: 60 },
      { name: "Elise", pickRate: 60 },
      { name: "Saizo", pickRate: 55 },
      { name: "Niles", pickRate: 55 },
      { name: "Silas", pickRate: 55 },
      { name: "Reina", pickRate: 50 },
      { name: "Effie", pickRate: 50 },
      { name: "Oboro", pickRate: 50 },
      { name: "Sakura", pickRate: 50 },
      { name: "Felicia", pickRate: 45 },
      { name: "Jakob", pickRate: 45 },
      { name: "Subaki", pickRate: 45 },
      { name: "Kaden", pickRate: 40 },
      { name: "Keaton", pickRate: 40 },
      { name: "Hinata", pickRate: 40 },
      { name: "Hana", pickRate: 40 },
      { name: "Selena", pickRate: 40 },
      { name: "Beruka", pickRate: 40 },
      { name: "Arthur", pickRate: 35 },
      { name: "Orochi", pickRate: 35 },
      { name: "Laslow", pickRate: 35 },
      { name: "Peri", pickRate: 35 },
      { name: "Setsuna", pickRate: 30 },
      { name: "Rinkah", pickRate: 30 },
      { name: "Azama", pickRate: 30 },
      { name: "Odin", pickRate: 30 },
      { name: "Charlotte", pickRate: 30 },
      { name: "Hayato", pickRate: 25 },
      { name: "Nyx", pickRate: 25 },
      { name: "Benny", pickRate: 25 },
      { name: "Flora", pickRate: 25 },
      { name: "Shura", pickRate: 25 },
      { name: "Mozu", pickRate: 20 },
      { name: "Fuga", pickRate: 20 },
      { name: "Gunter", pickRate: 15 },
    ],
  },
  { name: "Engage", slug: "en", 
    freeUnits: ["Alear","Vander","Seadall"], 
    units: [
      { name: "Clanne", pickRate: 0 },
      { name: "Framme", pickRate: 0 },
      { name: "Alfred", pickRate: 0 }, 
      { name: "Etie", pickRate: 0 },
      { name: "Boucheron", pickRate: 0 },
      { name: "Celine", pickRate: 0 }, 
      { name: "Chloe", pickRate: 0 },
      { name: "Louis", pickRate: 0 },
      { name: "Yunaka", pickRate: 0 }, 
      { name: "Alcryst", pickRate: 0 },
      { name: "Citrinne", pickRate: 0 },
      { name: "Lapis", pickRate: 0 }, 
      { name: "Diamant", pickRate: 0 },
      { name: "Amber", pickRate: 0 },
      { name: "Jade", pickRate: 0 }, 
      { name: "Ivy", pickRate: 0 },
      { name: "Kagetsu", pickRate: 0 },
      { name: "Zelkov", pickRate: 0 }, 
      { name: "Fogado", pickRate: 0 },
      { name: "Pandreo", pickRate: 0 },
      { name: "Bunet", pickRate: 0 }, 
      { name: "Timerra", pickRate: 0 },
      { name: "Panette", pickRate: 0 },
      { name: "Merrin", pickRate: 0 }, 
      { name: "Hortensia", pickRate: 0 },
      { name: "Rosado", pickRate: 0 },
      { name: "Goldmary", pickRate: 0 }, 
      { name: "Lindon", pickRate: 0 },
      { name: "Saphir", pickRate: 0 },
      { name: "Mauvier", pickRate: 0 }, 
      { name: "Veyle", pickRate: 0 },
      { name: "Jean", pickRate: 0 },
      { name: "Anna", pickRate: 0 }, 
    ],
   },
];
