const GAMES = [
  {
    name: "Sacred Stones",
    freeUnits: ["Eirika", "Ephraim"],
    units: [
      { name: "Seth", pickRate: 95 },
      { name: "Vanessa", pickRate: 80 },
      { name: "Franz", pickRate: 75 },
      { name: "Cormag", pickRate: 75 },
      { name: "Tana", pickRate: 70 },
      { name: "Gerik", pickRate: 70 },
      { name: "Duessel", pickRate: 65 },
      { name: "Tethys", pickRate: 60 },
      { name: "Saleh", pickRate: 60 },
      { name: "Lute", pickRate: 55 },
      { name: "Artur", pickRate: 55 },
      { name: "Joshua", pickRate: 50 },
      { name: "Myrrh", pickRate: 50 },
      { name: "Kyle", pickRate: 50 },
      { name: "Ross", pickRate: 45 },
      { name: "Forde", pickRate: 45 },
      { name: "Innes", pickRate: 45 },
      { name: "Moulder", pickRate: 40 },
      { name: "Gilliam", pickRate: 40 },
      { name: "Syrene", pickRate: 40 },
      { name: "Garcia", pickRate: 35 },
      { name: "Natasha", pickRate: 35 },
      { name: "Colm", pickRate: 35 },
      { name: "Dozla", pickRate: 35 },
      { name: "L'Arachel", pickRate: 30 },
      { name: "Neimi", pickRate: 30 },
      { name: "Amelia", pickRate: 25 },
      { name: "Knoll", pickRate: 25 },
      { name: "Ewan", pickRate: 20 },
      { name: "Marisa", pickRate: 20 },
      { name: "Rennac", pickRate: 15 },
    ],
  },
  { name: "Thracia 776", freeUnits: [], units: [] },
  { name: "Binding Blade", freeUnits: [], units: [] },
  { name: "Blazing Blade", freeUnits: [], units: [] },
  { name: "Path of Radiance", freeUnits: [], units: [] },
  { name: "Radiant Dawn", freeUnits: [], units: [] },
  { name: "Shadow Dragon", freeUnits: [], units: [] },
  { name: "New Mystery", freeUnits: [], units: [] },
  { name: "Awakening", freeUnits: [], units: [] },
  { name: "Fates Birthright", freeUnits: [], units: [] },
  { name: "Fates Conquest", freeUnits: [], units: [] },
  { name: "Fates Revelation", freeUnits: [], units: [] },
  { name: "Engage", freeUnits: [], units: [] },
];
